---
title: "R Notebook"
output: html_notebook
---
 - Let us load the 'Tidyverse' library package
 
```{r}
library(tidyverse)
library(data.table)
library(dplyr)
```

 - I am going to process the data sets in order to only display the information for Japan since it has the information from all the countries.
 
```{r}
percentage_of_land_covered_by_forest <- read_csv("../Data/forest-area-as-share-of-land-area.csv")

percentage_of_land_covered_by_forest <- percentage_of_land_covered_by_forest %>% 
  filter(Code == "JPN")
```
```{r}
percentage_of_land <- read_csv("../Data/forest-area-as-share-of-land-area.csv")

percentage_of_land <- percentage_of_land %>% 
  filter(Code == "JPN")

```

```{r}
number_of_trees <- read_csv("../Data/number-of-trees.csv")

number_of_trees <- number_of_trees %>% 
  filter(Code == "JPN")
```

```{r}
forest_area_km <- read_csv("../Data/forest-area-km.csv")

forest_area_km <- forest_area_km %>% 
  filter(Code == "JPN") %>% 
  rename(km_of_land = `Forest area` )
```


 
 
